### ISSUE TITLE
Windows exe

### ISSUE THREAD

**Issue by SzotsGabor** [DimitrijeDobrota/stellar#1]
Hello Dimitrije,

Could you provide exes for Windows please?

Gabor Szots,
CCRL testing group

**Comment by DimitrijeDobrota** [comment]
Thanks a lot for taking a interest in this project. 
You can find .exe for Windows in the [latest release](https://github.com/DimitrijeDobrota/stellar/releases/tag/v1.3). 
Let me know if you need any further assistance.

**Comment by SzotsGabor** [comment]
Thank you, it  works, only it displays 1.2.6 as version.

**Comment by DimitrijeDobrota** [comment]
Sorry about that, I've just uploaded the correct version.

**Comment by SzotsGabor** [comment]
I have started a tournament for our blitz list.
https://computerchess.org.uk/ccrl/404/rating_list_all.html
Next update is scheduled to 16th March.

**Comment by tissatussa** [comment]
what about a Linux version ?  I tried to compile but it fails .. v1.3 has same issue.

**Comment by DimitrijeDobrota** [comment]
Can you open a new issue and be more specific about the error you are getting? It would be helpful if you would paste the whole error for me to take a look at.

**Comment by tissatussa** [comment]
@DimitrijeDobrota thanks, i will.
[sorry to write into this closed issue]
