### ISSUE TITLE
Stellar in live broadcast - no other way to let you know

### ISSUE THREAD

**Issue by GrahamCCRL** [DimitrijeDobrota/stellar#4]
109TH AMATEUR SERIES (Division 11)

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU
The top engine will gain automatic promotion. Any other changes of division will be at my discretion and may not necessarily involve playoff matches.
Participants

CeeChess 1.4 64-bit (relegated)
Shen Yu 2.0.1 64-bit (relegated)
Oxidation 0.7.1 64-bit
Eubos 3.6 64-bit (relegated)
Isa 3.1 64-bit
Camel 1.6.0 64-bit
Tcheran 2.3 64-bit
Austerlitz 1.4.7 64-bit
chessplusplus 1.2.0 64-bit
Stellar 1.3.0 64-bit
InfraRed 2.0.2 64-bit
Trinket 3.0 64-bit
Maxwell 3.1.3 64-bit
Bread 0.4.0 64-bit (new)

Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16069

**Comment by DimitrijeDobrota** [comment]
Thanks a lot for letting me know.

Would it be possible in the future for you to use version 1.4.0 since I've made improvements to the performance and time management?

**Comment by GrahamCCRL** [comment]
Done. :-)
